# Generated by Django 2.0.13 on 2020-11-23 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField(default=0)),
                ('email', models.CharField(max_length=200)),
                ('transform', models.CharField(max_length=200)),
                ('distance', models.FloatField()),
                ('time', models.FloatField()),
            ],
        ),
    ]
